### ISSUE TITLE
Export job.freq

### ISSUE THREAD

**Issue by epelc** [albrow/jobs#16]
It would be useful if we could see the job frequency for recurring jobs.

**Comment by albrow** [comment]
@epelc Thanks for opening this. I can make job.freq accessible through a getter method easily, but making it settable in a safe way would require changing a lot of things about the underlying architecture. Is getting it could enough for you?

**Comment by epelc** [comment]
@albrow I just wanted a getter similar to `Key()` or `NextTime()`.

**Comment by albrow** [comment]
Okay thanks. I'll add this in 0.3.1.

**Comment by albrow** [comment]
Implemented in https://github.com/albrow/jobs/commit/22348b594c1ca3b16b656bbff4d57bd526f9fe43. I also added getter methods for a lot of the other fields. This will be included in version 0.3.1 on master.
