### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by epelc** [albrow/jobs#23]
I think it'd be nice if there was a changelog. This can either be done by hand or it can be automated if you force a syntax for commits ie `changeType(component): msg`. For an example of an automated changelog take a look at the [angular-material](https://github.com/angular/material) project. Their [changelog](https://github.com/angular/material/blob/master/CHANGELOG.md) is generated by the commit messages and then I think they tweak any problems with it before a release. That might be a bit much for this project but it let's you know what can be done. Either way I think a basic changelog would be really nice.

@albrow What do you think about this? I think it'd definitely make this easier to use in production.

**Comment by albrow** [comment]
@epelc I agree that this is important. I've already been posting release notes and a changelog for every release on the [releases page](https://github.com/albrow/jobs/releases). Whenever there are non-trivial breaking changes, I'll probably publish a migration guide, just like I have been doing with [zoom](https://github.com/albrow/zoom/wiki/Migration-Guide).

**Comment by epelc** [comment]
I forgot to check that. 9 times out of 10 no one fills It out. That's exactly what I was look for though.
